### ISSUE TITLE
一部の画像においてプレビューの向きが間違っている

### ISSUE THREAD

**Issue by rokoucha** [future-link/deltaweb#22]
fileで確認したけど元データの時点で間違った向きで格納されている(どういう仕様なのかは知らん)のでrotateする必要がありそう

**Comment by rokoucha** [comment]
EXIFのorientationを読めばよい

http://daredemopc.blog51.fc2.com/blog-entry-804.html

**Comment by rinsuki** [comment]
これはfileが返してくるサムネイルの問題なので https://github.com/misskey-delta/misskey-file へどうぞ

**Comment by rokoucha** [comment]
http://qiita.com/minodisk/items/b7bab1b3f351f72d534b

**Comment by rokoucha** [comment]
おっけー
